// Code generated by `just embed`. DO NOT EDIT.
//
// One entry per tracked template file, embedded at compile time so that `odin-skel new` needs
// neither a network nor a clone. Regenerate with `just embed`; `just embed-check` fails if this
// file no longer matches the repository.
package skel

TEMPLATES :: []Template {
	{path = ".editorconfig", data = #load("../../.editorconfig", string), sync = true},
	{path = ".gitattributes", data = #load("../../.gitattributes", string), sync = true},
	{path = ".gitignore", data = #load("../../.gitignore", string), sync = true},
	{path = ".just/editor.just", data = #load("../../.just/editor.just", string), sync = true},
	{path = ".just/toolchain.just", data = #load("../../.just/toolchain.just", string), sync = true},
	{
		path = ".sublime/Just-Odin-lib.sublime-snippet",
		data = #load("../../.sublime/Just-Odin-lib.sublime-snippet", string),
	},
	{path = ".sublime/Just-Odin.sublime-snippet", data = #load("../../.sublime/Just-Odin.sublime-snippet", string)},
	{
		path = ".sublime/Odin-skeleton.sublime-snippet",
		data = #load("../../.sublime/Odin-skeleton.sublime-snippet", string),
	},
	{path = ".sublime/Odin.sublime-build", data = #load("../../.sublime/Odin.sublime-build", string)},
	{
		path = ".sublime/OdinJustTarget.sublime-build",
		data = #load("../../.sublime/OdinJustTarget.sublime-build", string),
	},
	{
		path = ".sublime/odin-lang-skeleton.sublime-project",
		data = #load("../../.sublime/odin-lang-skeleton.sublime-project", string),
	},
	{path = "LICENSE", data = #load("../../LICENSE", string)},
	{path = "README.md", data = #load("../../README.md", string)},
	{path = "bench/README.md", data = #load("../../bench/README.md", string), feature = "bench"},
	{path = "bench/bench.just", data = #load("../../bench/bench.just", string), feature = "bench"},
	{path = "bench/bench.odin", data = #load("../../bench/bench.odin", string), feature = "bench"},
	{path = "bench/runner.odin", data = #load("../../bench/runner.odin", string), feature = "bench"},
	{path = "justfile", data = #load("../../justfile", string)},
	{path = "main.odin", data = #load("../../main.odin", string), kind = .Exe},
	{path = "mylib/examples/basic.odin", data = #load("../../mylib/examples/basic.odin", string), kind = .Lib},
	{path = "mylib/mylib.odin", data = #load("../../mylib/mylib.odin", string), kind = .Lib},
	{path = "mylib/mylib_test.odin", data = #load("../../mylib/mylib_test.odin", string), kind = .Lib},
	{path = "odinfmt.json", data = #load("../../odinfmt.json", string), sync = true},
}
